apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mailroom
  name: mailroom
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailroom
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mailroom
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb/factory?ssl=false
            - name: STOCKROOM_SERVER
              value: http://stockroom:8080/stockroom
            - name: spring_profiles_active
              value: mailroom
          image: rlkamradt/factory:0.0.1-SNAPSHOT
          name: mailroom
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
